# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccc410e5fe22b4e2c7f23d45946f81fc91e93c93de9748874e6ed4ea21cd5321c5d75a0437ae87b2e5218d97f73d13b42ab4faa9ea058e1f13a38e4ece970bd4

test:
  secret_key_base: 17cd97a70375653b557901d59a826ac5b10aaa5d45928e265d1e99470f639870be5ac362f3c6a1524896da6749e37becd870508461e4007b472b6a78bf8d56e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
